[package]
name = "rvc-tauri"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { version = "2.5", features = ["wry"] }
rvc-lib = { path = "../rvc-lib" }
tokio = { version = "1", features = ["rt", "macros"] }
